---
- name: Create tar and distribute
  hosts: all
  tasks:

    - name: Create tar file on control node
      community.general.archive:
        path: /tmp/*.pem
        dest: /tmp/certs.gz
      delegate_to: localhost
      run_once: true

    - name: Copy tar to remote hosts
      ansible.builtin.copy:
        src: /tmp/certs.gz
        dest: /tmp/certs.gz

    # - name: Unarchive a file that is already on the remote machine
    #   ansible.builtin.unarchive:
    #     src: /tmp/certs.gz
    #     dest: /home/ansible
    #     remote_src: yes    

    - name: Fetch file from remote host
      ansible.builtin.fetch:
        src: /tmp/certs.gz
        dest: /tmp/shared_data
        flat: yes  

    - name: Debug local path
      delegate_to: localhost
      run_once: true
      shell: |
        echo "Hostname:"
        hostname
        echo "Listing /tmp/test:"
        ls -l /tmp/test || echo "No dir"
