---
- name: Create tar and distribute
  hosts: all
  vars:
    csv_path: "/tmp/report.csv"
  tasks:

    # - name: Create tar file on control node
    #   community.general.archive:
    #     path: /tmp/*.pem
    #     dest: /tmp/certs.gz
    #   delegate_to: localhost
    #   run_once: true

    # - name: Copy tar to remote hosts
    #   ansible.builtin.copy:
    #     src: /tmp/certs.gz
    #     dest: /tmp/certs.gz

    # - name: Unarchive a file that is already on the remote machine
    #   ansible.builtin.unarchive:
    #     src: /tmp/certs.gz
    #     dest: /home/ansible
    #     remote_src: yes    

    # - name: Fetch file from remote host
    #   ansible.builtin.fetch:
    #     src: /tmp/certs.gz
    #     dest: /tmp/
    #     flat: yes  

    # - name: Debug local path
    #   delegate_to: localhost
    #   run_once: true
    #   shell: |
    #     echo "Hostname:"
    #     hostname
    #     echo "Listing /tmp/test:"
    #     ls -l /tmp/test || echo "No dir"

    - name: Run hostname command
      command: hostname
      register: hostname_output

    - name: Check system os version
      command: "grep PRETTY_NAME /etc/os-release"
      register: os_output

    - name: Check cpu of system
      shell: "lscpu | grep '^CPU(s):' | awk '{print $2}'"
      register: cpu_output
      changed_when: false

    - debug:
        msg: "cpu_count={{ cpu_output.stdout }}"
 
  
    - name: Check total memory space on server
      shell:  "free -h | grep '^CPU(s):' | awk '{print $2}'"
      register: memory_output
      changed_when: false
    
    - debug:
        msg: "memory_size={{ memory_output.stdout }}"

    - name: Check disk space 
      command: df -h
      register: disk_output    

    - name: Ensure the CSV file exists
      ansible.builtin.file:
        path: "{{ csv_path }}"
        state: touch

    - name: Insert CSV header at the beginning of the file
      ansible.builtin.lineinfile:
        path: "{{ csv_path }}"
        line: "hostname,os_version,cpu_value,memory_size,Disk_space"
        insertbefore: BOF
        state: present  

    - name: Append data row (Example loop or single entry)
      ansible.builtin.lineinfile:
        path: "{{ csv_path }}"
        line: "{{hostname_output.stdout}},{{os_output.stdout}},{{cpu_output.stdout}},{{memory_output.stdout}},{{disk_output.stdout}}"
        insertafter: EOF
        state: present    