---
- name: Linux server checklist
  hosts: all
  # become: yes

  tasks:
    - name: Show os details
      debug: 
        msg: "OS:{{ansible_distribution}} {{ansible_distribution_version}}"
        
    - name: show hostname
      debug: 
        msg: "Hostname:{{ansible_hostname}}"    