---
- name: copy file on target hosts
  hosts: all
  become: true
  tasks:    
    - name: check file exist or not
      command: ls -ld /tmp
      delegate_to: localhost
      
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /tmp/redhat.txt
        dest: /tmp

    # - name: check files are available or not
    #   command: "touch /tmp/testfile"
    #   register: command_output

    #   cert9.pem