---
- name: copy file on target hosts
  hosts: localhost
  tasks:

    - debug:
        msg: "{{ ansible_hostname }}"

    # - name : validate file exist or not
    #   shell: ssh ansible@192.168.10.229 

    - name: Run SSH command
      shell: sshpass -p 'x' ssh -o StrictHostKeyChecking=no ansible@192.168.10.229 "uptime" && \
             sshpass -p 'x' scp -o StrictHostKeyChecking=no /home/ansible/list-PocIP ansible@192.168.10.240:/tmp/

    # - name: Ensure file exist or not 
    #   command: ls -l /home/ansible/list-PocIP
    #   register: command_output

    # - debug: 
    #     var: "command_output.stdout"


    # - name: copy the file on target hosts
    #   ansible.builtin.copy:
    #     src: ./checklist.yml
    #     dest: /tmp

    # - name: Slurp the remote file
    #   ansible.builtin.slurp:
    #     src: /home/ansible/list-PocIP
    #   register: slurped_file

    # - name: Decode and print file content
    #   ansible.builtin.debug:
    #     msg: "The remote content is: {{ slurped_file['content'] | b64decode }}"  

