---
- name: copy file on target hosts
  hosts: localhost
  become: true
  tasks:
    - name: Create a directory with permissions
      ansible.builtin.file:
        path: /tmp
        state: directory

    - name: change file permissions
      command: "chown root:root /tmp"    
        

    - name: check files are available or not
      command: audo ls -l /tmp
      register: command_output