---
- name: copy file on target hosts
  hosts: all
  tasks:

    - debug:
        msg: "{{ ansible_hostname }}"

    # - name: Ensure file exist or not 
    #   command: ls -l /home/ansible/list-PocIP
    #   register: command_output

    # - debug: 
    #     var: "command_output.stdout"


    # - name: copy the file on target hosts
    #   ansible.builtin.copy:
    #     src: ./checklist.yml
    #     dest: /tmp

    - name: Slurp the remote file
      ansible.builtin.slurp:
        src: /tmp/checklist.yml
      register: slurped_file

    - name: Decode and print file content
      ansible.builtin.debug:
        msg: "The remote content is: {{ slurped_file['content'] | b64decode }}"  

