---
- name: Webhook Example
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Restart apache when alert received
      condition: event.payload.alert == "restart_apache"

      action:
        run_playbook:
          name: restart_service.yml